name: CI Pipeline - Train & Build Docker

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }} # Atau sesuaikan dengan nama secret token DagsHub Anda

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib
        sudo apt-get update && sudo apt-get install -y default-jre

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Train Model
      working-directory: ./MLProject
      env:
        MLFLOW_TRACKING_USERNAME: "andrianrv"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: python modelling.py

    - name: Build & Push Docker (Strategy: Local Build)
      working-directory: ./MLProject
      run: |
        echo "Building Docker from Local Model (model_output)..."
        
        # Perintah ini TIDAK download dari internet, tapi pakai file yang baru dibuat
        # Jadi tidak mungkin error "Failed to download"
        mlflow models build-docker \
          -m "model_output" \
          -n "${{ secrets.DOCKER_USERNAME }}/vgsales-model:latest" \
          --enable-mlserver

        docker push ${{ secrets.DOCKER_USERNAME }}/vgsales-model:latest