name: CI Pipeline - Train & Build Docker

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'

env:
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }} # Sesuaikan nama secret token DagsHub Anda

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn matplotlib
        sudo apt-get update && sudo apt-get install -y default-jre

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Train Model
      working-directory: ./MLProject
      env:
        MLFLOW_TRACKING_USERNAME: "andrianrv"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: python modelling.py

    - name: Read Run ID
      working-directory: ./MLProject
      run: |
        run_id=$(cat run_id.txt)
        echo "RUN_ID=$run_id" >> $GITHUB_ENV

    - name: Build & Push Docker
      run: |
        export MLFLOW_TRACKING_URI="https://dagshub.com/andrianrv/Eksperimen_SML_Andrian_Radita.mlflow"
        export MLFLOW_TRACKING_USERNAME="andrianrv"
        export MLFLOW_TRACKING_PASSWORD="${{ secrets.MLFLOW_TRACKING_PASSWORD }}"

        mlflow models build-docker \
          -m "runs:/${{ env.RUN_ID }}/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/vgsales-model:latest" \
          --enable-mlserver

        docker push ${{ secrets.DOCKER_USERNAME }}/vgsales-model:latest